"""
scripts/run_validation.py — Stimulus validation + behavioral gate for any thread.

Generates pairs, validates schema + frequency matching, runs behavioral gate,
saves results. Must pass before mechanistic experiment can run.

Usage (Colab):
    !python scripts/run_validation.py --thread t1a
    !python scripts/run_validation.py --thread t2
    !python scripts/run_validation.py --thread t2b
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ── Args ──────────────────────────────────────────────────────────────────────

parser = argparse.ArgumentParser()
parser.add_argument("--thread", required=True, help="Thread ID: t1a, t2, t2b, t1b, t1c, t3, t4, t5, t6")
args = parser.parse_args()

THREAD_ID = args.thread

# Single source of truth for the variant→base mapping — shared with the invariant
# gates in experiments/config.py so this script and the gates never disagree on
# what philosophical thread a per-model run ("t1a_gpt2", "t1a_pythia") belongs to.
from experiments.config import base_thread_of

BASE_THREAD = base_thread_of(THREAD_ID)
MODEL_VARIANT_SUFFIX = THREAD_ID[len(BASE_THREAD):]  # "" | "_gpt2" | "_pythia"

# Which model each run suffix loads. Stimuli are model-agnostic and live under the
# BASE thread; every per-model run reuses them and only re-runs its own gate.
MODEL_BY_SUFFIX: dict[str, str] = {
    "": "meta-llama/Llama-3.2-3B",   # bare base id defaults to primary (Llama) — 2026-06-13
    "_llama": "meta-llama/Llama-3.2-3B",
    "_gpt2": "gpt2-medium",
    "_pythia": "EleutherAI/pythia-1.4b",
}
if MODEL_VARIANT_SUFFIX not in MODEL_BY_SUFFIX:
    print("ERROR: unknown model suffix '" + MODEL_VARIANT_SUFFIX + "' on thread '" + THREAD_ID + "'.")
    print("Known suffixes: " + ", ".join(sorted(s for s in MODEL_BY_SUFFIX if s)))
    sys.exit(1)

# ── Paths ─────────────────────────────────────────────────────────────────────

GRAMMAR_FILE    = PROJECT_ROOT / "stimuli" / "grammars" / (BASE_THREAD + ".py")
GENERATED_PATH  = PROJECT_ROOT / "stimuli" / "generated" / BASE_THREAD / "pairs.jsonl"
VALIDATED_PATH  = PROJECT_ROOT / "stimuli" / "validated" / BASE_THREAD / "pairs.validated.jsonl"
GATE_RESULT_PATH = PROJECT_ROOT / "experiments" / THREAD_ID / "results" / "behavioral_gate.json"

if not GRAMMAR_FILE.exists():
    print("ERROR: Grammar file not found: " + str(GRAMMAR_FILE))
    sys.exit(1)

# Generation is LAZY and model-agnostic: the first run that needs the base thread's
# stimuli generates+validates them; later runs (other models) reuse them.
STIMULI_ALREADY_VALIDATED = VALIDATED_PATH.exists()

# Max pairs per base thread — full product space for each grammar. Variants reuse
# the base thread's stimuli, so they look up N_PAIRS by BASE_THREAD.
N_PAIRS_BY_THREAD: dict[str, int] = {
    "t1a": 300,
    "t1b": 300,
    "t1c": 150,
    "t1d": 120,
    "t2":  630,
    "t2b": 30,
    "t3":  300,
    "t4":  300,
    "t5":  300,
    "t6":  300,
}

if BASE_THREAD not in N_PAIRS_BY_THREAD:
    print("ERROR: Unknown thread '" + THREAD_ID + "'.")
    print("Known threads: " + ", ".join(sorted(N_PAIRS_BY_THREAD))
          + " (optionally with a " + "/".join(sorted(s for s in MODEL_BY_SUFFIX if s)) + " suffix)")
    sys.exit(1)

N_PAIRS = N_PAIRS_BY_THREAD[BASE_THREAD]

# ── Imports ───────────────────────────────────────────────────────────────────

from stimuli.pipeline import generate_pairs, validate_set, run_behavioral_gate
from core.io import save_result

# Load generate_behavioral_items from the thread's grammar module dynamically
grammar_spec = importlib.util.spec_from_file_location("grammar_module", GRAMMAR_FILE)
grammar_module = importlib.util.module_from_spec(grammar_spec)
grammar_spec.loader.exec_module(grammar_module)

# ── Pipeline ──────────────────────────────────────────────────────────────────

MODEL_NAME     = MODEL_BY_SUFFIX[MODEL_VARIANT_SUFFIX]
GATE_THRESHOLD = 0.70

print("=" * 60)
print("PoL-Probe — Validation Pipeline  [Thread: " + THREAD_ID + "]")
print("=" * 60)
print()

# Step 0: Load model ───────────────────────────────────────────────────────────
print("[Step 0] Loading model...")
print("  " + MODEL_NAME)

from transformer_lens import HookedTransformer
model = HookedTransformer.from_pretrained(MODEL_NAME)
model.eval()

print("  Loaded. n_layers=" + str(model.cfg.n_layers) + ", d_model=" + str(model.cfg.d_model))
print()

if STIMULI_ALREADY_VALIDATED:
    # Steps 1 & 2 skipped: stimuli already generated by an earlier per-model run.
    # Stimuli are model-agnostic; generation and validation need not repeat.
    print("[Step 1] Skipped — reusing existing base-thread stimuli (" + BASE_THREAD + ")")
    print("  Validated file: " + str(VALIDATED_PATH))
    print()
    print("[Step 2] Skipped — frequency matching already verified for base thread.")
    print()
    import json as _json_mod
    validated_pairs = []
    with VALIDATED_PATH.open("r") as _vf:
        for _line in _vf:
            _stripped = _line.strip()
            if _stripped:
                validated_pairs.append(_json_mod.loads(_stripped))
    print("  Loaded " + str(len(validated_pairs)) + " validated pairs.")
    print()
else:
    # Step 1: Generate ─────────────────────────────────────────────────────────
    print("[Step 1] Generating stimulus pairs...")
    print("  Grammar: " + str(GRAMMAR_FILE))
    print("  n=" + str(N_PAIRS))

    generated_pairs = generate_pairs(
        grammar_file=GRAMMAR_FILE,
        n=N_PAIRS,
        thread_id=BASE_THREAD,
    )

    print("  Generated: " + str(len(generated_pairs)) + " pairs")
    print("  Written to: " + str(GENERATED_PATH))
    print()

    # Step 2: Validate ─────────────────────────────────────────────────────────
    print("[Step 2] Validating pairs (schema + frequency matching)...")

    try:
        validated_pairs = validate_set(generated_pairs, thread_id=BASE_THREAD)
    except ValueError as validation_error:
        print()
        print("ERROR: validate_set() failed — all pairs rejected.")
        print("  " + str(validation_error))
        sys.exit(1)

    n_rejected = len(generated_pairs) - len(validated_pairs)

    # Count individual sentence labels (both sentence_a and sentence_b).
    # Pair-level label_a counts alone omit conditions that appear only as label_b.
    sentence_label_counts: dict[str, int] = {}
    for pair in validated_pairs:
        for label_key in ("label_a", "label_b"):
            label = pair.get(label_key, "unknown")
            sentence_label_counts[label] = sentence_label_counts.get(label, 0) + 1

    print("  Passed:   " + str(len(validated_pairs)) + " pairs")
    print("  Rejected: " + str(n_rejected) + " pairs")
    print("  Individual sentence counts by label:")
    for label, count in sorted(sentence_label_counts.items()):
        print("    " + label + ": " + str(count))
    print("  Written to: " + str(VALIDATED_PATH))
    print()

# Step 3: Behavioral gate ──────────────────────────────────────────────────────
print("[Step 3] Running behavioral gate...")
print("  Threshold: " + str(int(GATE_THRESHOLD * 100)) + "%")

behavioral_items = grammar_module.generate_behavioral_items()
print("  Scoring " + str(len(behavioral_items)) + " forced-choice items on " + MODEL_NAME + "...")

gate_result = run_behavioral_gate(
    behavioral_items=behavioral_items,
    model=model,
    threshold=GATE_THRESHOLD,
)

n_correct = round(gate_result["accuracy"] * gate_result["n_items"])
print("  Accuracy: " + str(round(gate_result["accuracy"] * 100, 1)) + "%  (" + str(n_correct) + "/" + str(gate_result["n_items"]) + " correct)")
print("  Passed:   " + str(gate_result["passed"]))
print()

# Step 4: Save ─────────────────────────────────────────────────────────────────
print("[Step 4] Saving gate result...")
save_result(gate_result, GATE_RESULT_PATH)
print("  Written to: " + str(GATE_RESULT_PATH))
print()

# ── Summary ───────────────────────────────────────────────────────────────────

print("=" * 60)
if gate_result["passed"]:
    print("RESULT: PASS")
    print()
    print("Output files:")
    if not STIMULI_ALREADY_VALIDATED:
        print("  " + str(GENERATED_PATH))
        print("  " + str(VALIDATED_PATH))
    else:
        print("  (stimuli reused from base thread " + BASE_THREAD + ")")
    print("  " + str(GATE_RESULT_PATH))
    print()
    print("Next: run the experiment script for thread " + THREAD_ID + ".")
    sys.exit(0)
else:
    print("RESULT: FAIL")
    print()
    print("  Behavioral gate did not pass.")
    print("  Accuracy " + str(round(gate_result["accuracy"] * 100, 1)) + "% is below threshold " + str(int(GATE_THRESHOLD * 100)) + "%.")
    print()
    print("  Run scripts/inspect_gate.py --thread " + THREAD_ID + " to see which items failed.")
    sys.exit(1)
